CREATE TABLE IF NOT EXISTS `cities` (
	`id` INTEGER AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `wards` (
	`id` INTEGER AUTO_INCREMENT,
	`cityId` INTEGER NOT NULL,
	`name` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `users` (
	`id` INTEGER AUTO_INCREMENT,
	`fullName` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL UNIQUE,
	`password` VARCHAR(255) NOT NULL,
	`phone` VARCHAR(20),
	`status` ENUM('ACTIVE', 'PENDING', 'BLOCKED') NOT NULL DEFAULT 'ACTIVE',
	`role` ENUM('ADMIN', 'PARTNER', 'CUSTOMER') NOT NULL,
	`address` VARCHAR(255),
	`gender` ENUM('MALE', 'FEMALE', 'OTHER'),
	`birthDate` DATE,
	`avatarUrl` VARCHAR(255),
	`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`cityId` INTEGER,
	`wardId` INTEGER,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `partners` (
	`id` INTEGER AUTO_INCREMENT UNIQUE,
	`userId` INTEGER,
	`companyName` VARCHAR(255) NOT NULL UNIQUE,
	`taxCode` VARCHAR(100) NOT NULL,
	`businessLicense` JSON NOT NULL,
	PRIMARY KEY(`userId`)
);


CREATE TABLE IF NOT EXISTS `hotels` (
	`id` INTEGER AUTO_INCREMENT,
	`partnerId` INTEGER NOT NULL,
	`hotelName` VARCHAR(255) NOT NULL,
	`description` TEXT,
	`rating` FLOAT DEFAULT 0,
	`cityId` INTEGER NOT NULL,
	`wardId` INTEGER NOT NULL,
	`address` TEXT NOT NULL,
	`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`img` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `roomTypes` (
	`id` INTEGER AUTO_INCREMENT,
	`typeName` VARCHAR(255) NOT NULL,
	`description` TEXT,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `bedTypes` (
	`id` INTEGER AUTO_INCREMENT,
	`bedName` VARCHAR(255) NOT NULL,
	`maxPeople` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `roomConfigurations` (
	`id` INTEGER AUTO_INCREMENT,
	`hotelId` INTEGER NOT NULL,
	`roomTypeId` INTEGER NOT NULL,
	`price` DECIMAL(12,2) NOT NULL,
	`area` INTEGER NOT NULL,
	`baseQuantity` INTEGER NOT NULL,
	`bedQuantity` INTEGER NOT NULL DEFAULT 1,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `physicalRooms` (
	`id` INTEGER AUTO_INCREMENT,
	`roomConfigId` INTEGER NOT NULL,
	`roomNumber` VARCHAR(50) NOT NULL,
	`floor` INTEGER,
	`status` ENUM('AVAILABLE', 'MAINTENANCE', 'OCCUPIED', 'BLOCKED') NOT NULL DEFAULT 'AVAILABLE',
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `roomImages` (
	`id` INTEGER AUTO_INCREMENT,
	`roomConfigId` INTEGER NOT NULL,
	`imageUrl` VARCHAR(255) NOT NULL,
	`isPrimary` BOOLEAN DEFAULT false,
	`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `amenities` (
	`id` INTEGER AUTO_INCREMENT,
	`amenityName` VARCHAR(255) NOT NULL,
	`icon` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `roomAmenities` (
	`roomConfigId` INTEGER NOT NULL,
	`amenityId` INTEGER NOT NULL,
	PRIMARY KEY(`roomConfigId`, `amenityId`)
);


CREATE TABLE IF NOT EXISTS `booking` (
	`id` INTEGER AUTO_INCREMENT,
	`bookingDetailId` INTEGER NOT NULL,
	`userId` INTEGER NOT NULL,
	`totalAmount` DECIMAL(12,0) NOT NULL,
	`platformFee` DECIMAL(12,0) NOT NULL,
	`partnerRevenue` DECIMAL(12,0) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `reviews` (
	`id` INTEGER AUTO_INCREMENT,
	`hotelId` INTEGER NOT NULL,
	`userId` INTEGER NOT NULL,
	`bookingDetailId` INTEGER NOT NULL UNIQUE,
	`rating` INTEGER CHECK(`rating` >= 1 AND `rating` <= 5),
	`content` TEXT NOT NULL,
	`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`status` ENUM('DISPLAY', 'HIDDEN') NOT NULL DEFAULT 'DISPLAY',
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `payments` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`bookingDetailId` INTEGER NOT NULL,
	`amount` DECIMAL NOT NULL,
	`paymentMethod` ENUM('MOMO', 'VNPAY') NOT NULL,
	`paymentStatus` ENUM('PENDING', 'PAID', 'FAILED', 'REFUNDED') NOT NULL,
	`createdAt` TIMESTAMP NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `bookingDetail` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`voucherId` INTEGER,
	`checkIn` DATETIME NOT NULL,
	`checkOut` DATETIME NOT NULL,
	`createdAt` TIMESTAMP NOT NULL,
	`note` TEXT(65535) NOT NULL,
	`amount` DECIMAL NOT NULL,
	`physicalRoomId` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `vouchers` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`code` VARCHAR(255) NOT NULL,
	`quantity` INTEGER NOT NULL,
	`type` ENUM('PERCENT', 'FIXED') NOT NULL,
	`amount` DECIMAL NOT NULL,
	`condition` DECIMAL NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `roomConfigtion_bedType` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`roomId` INTEGER NOT NULL,
	`bedTypeId` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


ALTER TABLE `wards`
ADD FOREIGN KEY(`cityId`) REFERENCES `cities`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `partners`
ADD FOREIGN KEY(`userId`) REFERENCES `users`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `hotels`
ADD FOREIGN KEY(`partnerId`) REFERENCES `partners`(`userId`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `hotels`
ADD FOREIGN KEY(`cityId`) REFERENCES `cities`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `hotels`
ADD FOREIGN KEY(`wardId`) REFERENCES `wards`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `roomConfigurations`
ADD FOREIGN KEY(`hotelId`) REFERENCES `hotels`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `roomConfigurations`
ADD FOREIGN KEY(`roomTypeId`) REFERENCES `roomTypes`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `physicalRooms`
ADD FOREIGN KEY(`roomConfigId`) REFERENCES `roomConfigurations`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `roomImages`
ADD FOREIGN KEY(`roomConfigId`) REFERENCES `roomConfigurations`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `roomAmenities`
ADD FOREIGN KEY(`roomConfigId`) REFERENCES `roomConfigurations`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `roomAmenities`
ADD FOREIGN KEY(`amenityId`) REFERENCES `amenities`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `booking`
ADD FOREIGN KEY(`userId`) REFERENCES `users`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `reviews`
ADD FOREIGN KEY(`hotelId`) REFERENCES `hotels`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `reviews`
ADD FOREIGN KEY(`userId`) REFERENCES `users`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `users`
ADD FOREIGN KEY(`cityId`) REFERENCES `cities`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `users`
ADD FOREIGN KEY(`wardId`) REFERENCES `wards`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `reviews`
ADD FOREIGN KEY(`bookingDetailId`) REFERENCES `bookingDetail`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `booking`
ADD FOREIGN KEY(`bookingDetailId`) REFERENCES `bookingDetail`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `payments`
ADD FOREIGN KEY(`bookingDetailId`) REFERENCES `bookingDetail`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `bookingDetail`
ADD FOREIGN KEY(`voucherId`) REFERENCES `vouchers`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `roomConfigtion_bedType`
ADD FOREIGN KEY(`roomId`) REFERENCES `roomConfigurations`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `roomConfigtion_bedType`
ADD FOREIGN KEY(`bedTypeId`) REFERENCES `bedTypes`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `bookingDetail`
ADD FOREIGN KEY(`physicalRoomId`) REFERENCES `physicalRooms`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;